[workspace]
members = [
    "crates/difftest-core",
    "crates/difftest-cli",
    "crates/difftest-python",
]
default-members = [
    "crates/difftest-core",
    "crates/difftest-cli",
]
resolver = "2"
